plugins {
    id 'com.android.application'
}

android {
    namespace 'com.handling.editor'
    compileSdk 36

    defaultConfig {
        applicationId 'com.handling.editor'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile(
                'proguard-android-optimize.txt'
            ), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(
        dir: 'libs',
        include: ['*.jar']
    )

    implementation 'dev.rikka.shizuku:api:13.1.5'
}
